name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Get current date as version
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      
        
      
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag codemohitpra2103/multiple-disease-detection-frontend:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin
        docker push codemohitpra2103/multiple-disease-detection-frontend
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set permissions for private key
        env:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            HOSTNAME: ${{secrets.HOSTNAME}}
            USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
      - name: Pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.USER_NAME}}@${{secrets.HOSTNAME}} 'sudo docker pull codemohitpra2103/multiple-disease-detection-frontend:latest'
      - name: Stop running container
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.USER_NAME}}@${{secrets.HOSTNAME}} 'sudo docker stop multiple-disease-detection-frontend || true'
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.USER_NAME}}@${{secrets.HOSTNAME}} 'sudo docker rm multiple-disease-detection-frontend || true'
      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.USER_NAME}}@${{secrets.HOSTNAME}} 'sudo docker run -d --name multiple-disease-detection-frontend -p 80:3000 codemohitpra2103/multiple-disease-detection-frontend:latest'
